# Generated by Django 5.1 on 2024-10-08 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_attribute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='text',
            field=models.CharField(default='text', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
        ),
    ]
